### ISSUE TITLE
Extern ip adress

### ISSUE THREAD

**Issue by Julusmoen** [spaddlewit/ShellySwitcher#1]
Hello! Is it possible to get an option for external ip address with ports? This app doesn’t work #airside my home! My Shelley is mounted on a garage door.

Hope for a solution! Very nice app😊

**Comment by spaddlewit** [comment]
Do you mean using Shelly cloud? Or simply any external IP address that has a port wide open to the public internet (I doubt you'd want to do this, since anybody could control your shelly!)

**Comment by Julusmoen** [comment]
Hello yes I want an option for external ip in the app because it doesn’t
work before I’m my WiFi area.

tor. 29. apr. 2021 kl. 22:12 skrev spaddlewit ***@***.***>:

**Comment by Julusmoen** [comment]
Had been nice with this option😊 a port wide open will be fine!

tor. 29. apr. 2021 kl. 22:12 skrev spaddlewit ***@***.***>:

**Comment by spaddlewit** [comment]
Ok, I understand. An external IP should already be possible, but I will add a feature to specify a port number also.

**Comment by Julusmoen** [comment]
Nice👌 Yes with specified port😊

tor. 29. apr. 2021 kl. 22:50 skrev spaddlewit ***@***.***>:

**Comment by spaddlewit** [comment]
Please join the TestFlight beta and let me know if the changes work for you:

https://testflight.apple.com/join/Ews5hWE4

**Comment by Julusmoen** [comment]
Hello! The external IP address was written and a chosen port same port on
udp and tcp but the switch is only grey and no contact.

Router has port forwarding on internal IP address with the same chosen port.

søn. 2. mai 2021 kl. 14:34 skrev spaddlewit ***@***.***>:

**Comment by spaddlewit** [comment]
My apologies, please try Build 3.

**Comment by Julusmoen** [comment]
No same response! No connection.

søn. 2. mai 2021 kl. 22:37 skrev spaddlewit ***@***.***>:

**Comment by spaddlewit** [comment]
Does the switch work when you tap the button, at least?

Does it work if you access http://address:port/relay/0 in Safari on your iPhone?

**Comment by Julusmoen** [comment]
No the button is only grey…

This is from the web

http:// address:port/relay/0?turn=on (work)

{"ison":true,"has_timer":false,"timer_started":0,"timer_duration":0,"timer_remaining":0,"source":"http"}


man. 3. mai 2021 kl. 13:04 skrev spaddlewit ***@***.***>:

**Comment by Julusmoen** [comment]
I tried it one more time! When you are choosing switch type Shelly and it’s
marked green you have to tap on it several of time for it to confirm it.
Now it is working👌😊

man. 3. mai 2021 kl. 13:10 skrev Tor Erling Julusmoen ***@***.***>:

**Comment by Julusmoen** [comment]
Is it possible to make the switch to toggle switch? And icon in the watch
in the shortcut is only a white box.
But it’s working👌

man. 3. mai 2021 kl. 13:18 skrev Tor Erling Julusmoen ***@***.***>:

**Comment by spaddlewit** [comment]
I will try to fix the complication icon -- it can be hard to test it sometimes because the watch doesn't update it frequently.

You use a toggle switch for a garage door opener? Usually those are just switch on. Make sure you set your shelly to automatically switch it off after 1 second via the Shelly app.

**Comment by Julusmoen** [comment]
Ok thank you! The shelly is set to toggle but in use of the app on the
watch I have to push button two times to trigger Shelly. Maybe I have to
set it to momentary?

man. 3. mai 2021 kl. 15:46 skrev spaddlewit ***@***.***>:

**Comment by spaddlewit** [comment]
That's what I do - I set it to automatically turn off after 1 second. I have the Shelly 1 wired to simulate the 'button press' on the wall, which momentarily closes the circuit.

**Comment by Julusmoen** [comment]
Tested with momentary work perfectly👌😊 thx!

man. 3. mai 2021 kl. 16:12 skrev spaddlewit ***@***.***>:
